-- tu runuj wszystko po koleji


--Usługa: 
--Id [INTEGER, NOT NULL, PRIMARY KEY], 
--Nazwa [VARCHAR(100), NOT NULL], 
--Cena [NUMBER(6,2), NOT NULL], 
-- Czas_wykonania[Number(6), NOT NULL]

CREATE TYPE SERVICE_t AS OBJECT (
    ID INTEGER,
    NAME VARCHAR2(100),
    PRICE NUMBER(6,2),
    COMPLETION_TIME NUMBER(6),
    QUALIFICATION_LEVEL VARCHAR(30)
);

CREATE TYPE SERVICE_NTAB_REF AS TABLE OF REF SERVICE_t;


--Zlecenie: 
--Id [INTEGER, NOT NULL, PRIMARY KEY], 
--Godzina [DATE, NOT NULL]
--Status[Varchar(30)] 
--Koszt [NUMBER(6,2), NOT NULL], 
--Id_Usług [INTEGER, REFERENCE Usługi.Id, NESTED TABLE] 

CREATE TYPE COMMISION_t AS OBJECT (
    ID INTEGER,
    DATE_ DATE,
    STATUS VARCHAR2(30),
    PRICE NUMBER(6,2),
    SERVICES SERVICE_NTAB_REF
);

CREATE TYPE COMMISION_NTAB_REF AS TABLE OF REF COMMISION_t;

CREATE TYPE CLIENT_COMMISION_NTAB_REF AS TABLE OF REF COMMISION_t;

--Klient: 
--Id [INTEGER, NOT NULL, PRIMARY KEY] 
--Imię [varchar(30), NOT NULL], 
--Nazwisko[varchar(30), NOT NULL], 
--Id_Zleceń[INTEGER, REFERENCE Zlecenia.Id, NESTED TABLE] 
--Nr_telefonu [VARCHAR(9)] 
--Email [VARCHAR(200)] 
--Płeć [VARCHAR(1), NOT NULL] 

CREATE TYPE CLIENT_t AS OBJECT (
    ID INTEGER,
    NAME VARCHAR2(30),
    SECOND_NAME VARCHAR2(30),
    COMMISIONS CLIENT_COMMISION_NTAB_REF,
    PHONE VARCHAR2(9),
    EMAIL VARCHAR2(100),
    GENDER VARCHAR2(1)
);

--Grafik:
--Id [INTEGER, NOT NULL, PRIMARY KEY]
--Data [DATE]
--Godzina_Od  [DATE]
--Godzina_Do [DATE]
--Id_Zleceń [INTEGER , REFERENCE Zlecenie.Id, NESTED TABLE]

CREATE TYPE GRAPHIC_t AS OBJECT (
    ID INTEGER,
    DAY DATE,
    START_HOURS DATE,
    END_HOURS DATE,
    COMMISIONS COMMISION_NTAB_REF
);

CREATE TYPE GRAPHIC_NTAB_REF AS TABLE OF REF GRAPHIC_t;

--Pracownik: 
--Id [INTEGER, NOT NULL, PRIMARY KEY], 
--Imie [varchar(30), NOT NULL], 
--Nazwisko[varchar(30), NOT NULL], 
--Data_Zatrudnienia [DATE NOT NULL]
--Poziom_kwalfikacji[varchar(30), NOT NULL], 
--Id_Grafiku [INTEGER, REFERENCE Grafik.Id, NESTED TABLE] 
--Pesel [VARCHAR(11), NOT NULL] 
--Pensja [NUMBER(6,2), NOT NULL] 
--Premia [NUMBER(6,2)] 

CREATE TYPE EMPLOYEE_t AS OBJECT (
    ID INTEGER,
    NAME VARCHAR2(30),
    SECOND_NAME VARCHAR2(30),
    DATE_OF_EMPLOYMENT DATE,
    POSITION VARCHAR2(30),
    GRAPHICS GRAPHIC_NTAB_REF,
    PESEL VARCHAR2(11),
    SALARY NUMBER(6,2),
    BONUS NUMBER(6,2)
);

CREATE TYPE EMP_NTAB_REF AS TABLE OF REF EMPLOYEE_t;

--Wyposażenie: 
--Id [INTEGER, NOT NULL, PRIMARY KEY], 
--Nazwa [VARCHAR(100), NOT NULL], 
--Ilość [INTEGER, NOT NULL], 
--Cena [NUMBER(7,2), NOT NULL] 

CREATE TYPE EQUIPMENT_t AS OBJECT (
    ID INTEGER,
    NAME VARCHAR2(100),
    AMOUNT INTEGER,
    PRICE NUMBER(7,2)
);

CREATE TYPE EQ_NTAB_REF AS TABLE OF REF EQUIPMENT_t;

--Placówka: 
--Id [INTEGER, NOT NULL, PRIMARY KEY], 
--Adres [VARCHAR(200), NOT NULL] 
--Id_wyposażenia [INTEGER, REFERENCE Wyposażenie.Id, NESTED TABLE] 
--Id_Pracowników [INTEGER, REFERENCE Pracownik.Id, NESTED TABLE] 
--Nr_telefonu [VARCHAR(9)] 

CREATE OR REPLACE TYPE SALON_t AS OBJECT (
    ID INTEGER,
    ADDRESS VARCHAR2(200),
    EQUIPMENTS EQ_NTAB_REF,
    EMPLOYEES EMP_NTAB_REF,
    PHONE VARCHAR2(9)
);


CREATE TYPE SALON_NTAB_REF AS TABLE OF REF SALON_t;

--Salon Fryzjerski: 
--Nazwa[varchar(30), NOT NULL], 
--CEO[varchar(100), NOT NULL], 
--Id_Placówek[INTEGER, REFERENCE Placówka.Id,NESTED TABLE] 

CREATE TYPE HAIRDRESSER_SALON_t AS OBJECT (
    NAME VARCHAR2(30),
    OWNER VARCHAR2(100),
    ID_SALON INTEGER,
    SALONS SALON_NTAB_REF
);


-- tabele obiektowe

CREATE TABLE SERVICE_tab OF SERVICE_t
(
    NAME NOT NULL,
    CONSTRAINT service_pk PRIMARY KEY (ID)
);

--------

CREATE TABLE COMMISION_tab OF COMMISION_t
(
    CONSTRAINT commision_pk PRIMARY KEY (ID)
)
NESTED TABLE SERVICES STORE AS comm_serv_refs_nt;

-- 3. Klient: COMMISIONS to kolekcja REFów. 
-- Nie definiujemy tu SERVICES, bo SERVICES "siedzą" w tabeli COMMISION_tab
CREATE TABLE CLIENT_tab OF CLIENT_t 
(
    CONSTRAINT client_pk PRIMARY KEY (ID)
)
NESTED TABLE COMMISIONS STORE AS client_comm_refs_nt;

-- 4. Grafik: Analogicznie - przechowujemy tylko REFy do zleceń
CREATE TABLE GRAPHIC_tab OF GRAPHIC_t
(
    CONSTRAINT graphic_pk PRIMARY KEY (ID)
)
NESTED TABLE COMMISIONS STORE AS graph_comm_refs_nt;

-- 5. Pracownik: Tylko poziom GRAPHICS
CREATE TABLE EMPLOYEE_tab OF EMPLOYEE_t 
(
    SECOND_NAME NOT NULL,
    CONSTRAINT employee_pk PRIMARY KEY (ID)
)
OBJECT IDENTIFIER IS PRIMARY KEY
NESTED TABLE GRAPHICS STORE AS emp_graph_refs_nt;

-- 6. Salon: Tutaj przechowujesz listy REF do sprzętu i pracowników
CREATE TABLE SALON_tab OF SALON_t 
(
    CONSTRAINT salon_pk PRIMARY KEY (ID)
)
NESTED TABLE EQUIPMENTS STORE AS salon_eq_refs_nt
NESTED TABLE EMPLOYEES STORE AS salon_emp_refs_nt;

-- 7. Salon Fryzjerski (Sieć):
CREATE TABLE HAIRDRESSER_SALON_tab OF HAIRDRESSER_SALON_t 
(
    CONSTRAINT hs_pk PRIMARY KEY (ID_SALON)
)
NESTED TABLE SALONS STORE AS hs_salons_refs_nt;

CREATE TABLE EQUIPMENT_tab OF EQUIPMENT_t
(
    CONSTRAINT equipment_pk PRIMARY KEY (ID)
);



-- kod do usuniecia wszystkich tabel
DROP TABLE HAIRDRESSER_SALON_tab CASCADE CONSTRAINTS;
DROP TABLE SALON_tab CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE_tab CASCADE CONSTRAINTS;
DROP TABLE GRAPHIC_tab CASCADE CONSTRAINTS;
DROP TABLE CLIENT_tab CASCADE CONSTRAINTS;
DROP TABLE COMMISION_tab CASCADE CONSTRAINTS;
DROP TABLE EQUIPMENT_tab CASCADE CONSTRAINTS;
DROP TABLE SERVICE_tab CASCADE CONSTRAINTS;



CREATE SEQUENCE seq_service START WITH 1;
CREATE SEQUENCE seq_commision START WITH 1;
CREATE SEQUENCE seq_client START WITH 1;
CREATE SEQUENCE seq_graphic START WITH 1;
CREATE SEQUENCE seq_employee START WITH 1;
CREATE SEQUENCE seq_equipment START WITH 1;
CREATE SEQUENCE seq_salon START WITH 1;


-- kod do usuniecia wszystkich typoww
-- polecam runowac kod po kolei  po kazdej linijce bo  inaczej moze ci nie dzialac
DROP TYPE HAIRDRESSER_SALON_t;
DROP TYPE SALON_NTAB_REF;
DROP TYPE SALON_t;

DROP TYPE EMP_NTAB_REF;
DROP TYPE EMPLOYEE_t;
DROP TYPE EQ_NTAB_REF;
DROP TYPE EQUIPMENT_t;

DROP TYPE GRAPHIC_NTAB_REF;
DROP TYPE GRAPHIC_t;
DROP TYPE CLIENT_t;
DROP TYPE CLIENT_COMMISION_NTAB_REF;

DROP TYPE COMMISION_NTAB_REF;
DROP TYPE COMMISION_t;
DROP TYPE SERVICE_NTAB_REF;
DROP TYPE SERVICE_t;
DROP SEQUENCE seq_service;
DROP SEQUENCE seq_commision;
DROP SEQUENCE seq_client;
DROP SEQUENCE seq_graphic;
DROP SEQUENCE seq_employee;
DROP SEQUENCE seq_equipment;
DROP SEQUENCE seq_salon;



-- Procedura zwiększania wyposażenia

